[phpenv]
version = "8.2.12"

[phpextensions]
pdo = "latest"
pdo_mysql = "latest"
gd = "latest"
zip = "latest"

[nodejs]
version = "18"

[build]
command = "composer install --no-dev --optimize-autoloader && npm install && npm run build"

[start]
command = "echo '=== Starting Database Migrations ===' && php artisan migrate --force && echo '=== Creating Storage Link ===' && php artisan storage:link && echo '=== Starting Server ===' && php -S 0.0.0.0:$PORT public/index.php"