[phases.setup]
nixPkgs = ["php82", "php82Packages.composer"]

[phases.install]
cmds = ["composer install --ignore-platform-reqs"]

[phases.build]
cmds = ["composer install --optimize-autoloader --no-dev"]

[start]
cmd = "php artisan migrate --force && php artisan storage:link && php artisan config:cache && vendor/bin/heroku-php-apache2 public/"