[phases.setup]
nixPkgs = ["php82", "php82Extensions.pdo", "php82Extensions.pdo_mysql", "php82Extensions.gd", "php82Extensions.zip", "php82Extensions.mbstring", "nginx", "nodejs-18_x", "composer"]

[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "npm install",
    "npm run build"
]

[start]
cmd = "php -d upload_max_filesize=100M -d post_max_size=100M artisan migrate --force && php artisan db:seed --force && php artisan storage:link && php -d upload_max_filesize=100M -d post_max_size=100M -S 0.0.0.0:$PORT -t public"