# Nixpacks Configuration for Railway Deployment
# Laravel Course Management System

# Setup Phase - Install Required Packages
[phases.setup]
nixPkgs = [
    "php82",
    "php82Extensions.pdo",
    "php82Extensions.pdo_mysql",
    "php82Extensions.gd",
    "php82Extensions.zip",
    "php82Extensions.mbstring",
    "nginx"
]

# Install Phase - Dependencies
[phases.install]
cmds = [
    "composer install --no-dev --optimize-autoloader --no-interaction",
    "npm install",
    "npm run build"
]

# Build Phase - Cache Configuration
[phases.build]
cmds = [
    "php artisan config:cache",
    "php artisan route:cache",
    "php artisan view:cache"
]

# Start Command - Migration, Seeding, and Server
[start]
cmd = "php -d upload_max_filesize=100M -d post_max_size=100M -d memory_limit=512M artisan migrate --force && php -d upload_max_filesize=100M -d post_max_size=100M artisan db:seed --force && php -d upload_max_filesize=100M -d post_max_size=100M artisan storage:link && php -d upload_max_filesize=100M -d post_max_size=100M -d memory_limit=512M -S 0.0.0.0:$PORT -t public"