[phpenv]
version = "8.2.12"

[phpextensions]
pdo = "latest"
pdo_mysql = "latest"
gd = "latest"
zip = "latest"

[nodejs]
version = "18"

[build]
command = "composer install --no-dev --optimize-autoloader && npm install && npm run build"

[start]
command = "echo '=== Starting Database Migrations ===' && php -d upload_max_filesize=100M -d post_max_size=100M -d memory_limit=256M artisan migrate --force && echo '=== Seeding Database ===' && php -d upload_max_filesize=100M -d post_max_size=100M artisan db:seed --force && echo '=== Creating Storage Link ===' && php -d upload_max_filesize=100M -d post_max_size=100M artisan storage:link && echo '=== Starting Server ===' && php -d upload_max_filesize=100M -d post_max_size=100M -d memory_limit=256M -S 0.0.0.0:$PORT public/index.php"