[phpenv]
version = "8.2.12"

[phpextensions]
pdo = "latest"
pdo_mysql = "latest"
gd = "latest"
zip = "latest"

[nodejs]
version = "18"

[build]
command = "composer install --no-dev --optimize-autoloader && npm install && npm run build"

[start]
command = "php artisan migrate --force && php artisan storage:link && php -S 0.0.0.0:$PORT public/index.php"