[build]
builder = "nixpacks"

[deploy]
startCommand = "php -d upload_max_filesize=100M -d post_max_size=100M -d memory_limit=512M -d max_execution_time=300 artisan migrate --force && php artisan db:seed --force && php artisan storage:link && php -d upload_max_filesize=100M -d post_max_size=100M -d memory_limit=512M -d max_execution_time=300 artisan serve --host=0.0.0.0 --port=$PORT"