[build]
builder = "nixpacks"

[deploy]
startCommand = "php artisan config:clear && php artisan cache:clear && php artisan migrate --force && php artisan storage:link && php -d upload_max_filesize=100M -d post_max_size=100M -d memory_limit=512M artisan serve --host=0.0.0.0 --port=$PORT"